### ISSUE TITLE
Upload logo not working

### ISSUE THREAD

**Issue by LucasNagy** [Non0reo/ImgToShader#2]
It doesn't allow me to press upload logo, nor uplaod background image or any position settings

**Comment by LoneDev6** [comment]
Yup, seems the `loadLogo` function doesn't even exist

**Comment by EvertBt** [comment]
'Future updates are going to let you put images in the background, or make a color gradient on the background.'
- in readme.md
It does not seem to be implemented yet, which should explain your issue

**Comment by Non0reo** [comment]
I'm indeed looking for a good algorithm which would convert an image into GLSL code that would be efficient and optimized. I may work on that later

**Comment by LucasNagy** [comment]
since that first comment i actually asked around and got help making something work

[Titruc](https://www.planetminecraft.com/member/titruc/) made some code that turns images into GLSL and got it working togheter with your ImgToShader gen for a [pack](https://www.planetminecraft.com/texture-pack/avocado-loading-screen/) of his:
https://www.mediafire.com/file/3lj7cmcdglh3bgz/gen.zip/file

But this doesn't display at all on anything but mac and has a lot of issues constantly breaking and not centering. So I got a friend of mine, [Maxboxx](https://twitter.com/maxboxx3) to try to fix it. Which he actually did!

And if you'd like to take a look at how its done they probably don't have anything agaisnt you basing your gen on this, maybe credit them.

[This texture pack](https://www.mediafire.com/file/c57hjcjo0th4pnd/90gQ_Resource_Pack_20.1.zip/file) has the fully working shader. The only problem is that it cannot from what I've seen load the shader if any of the files has more than 712 lines of code

**Comment by Non0reo** [comment]
Titruc told me about his method to display his image on screen
I took a look at the resource pack and I seems to be more or less the same concept. The way it's implemented though is not really optimized for higher res images (Actually it's the same method I used in my code in the beginning). But I should implement this algorithm for pixel art or small res images, and implement another algorithm for bigger images

**Comment by Non0reo** [comment]
Okay, I updated the generator to allow image upload. Only the background upload is available for now but I will add the logo upload soon. I also credited Maxboxx for the bit of code he wrote.
Though, the shader algorithm is also different as I will make multiple algorithms to have the choice of which one to use like I said in my pervious message.
Thanks for the feedback 👍
