### ISSUE TITLE
Generate / Download button not working entirely

### ISSUE THREAD

**Issue by vadim-soude** [Non0reo/ImgToShader#3]
I tried to use the tool this morning but the generate part seems broken.

In the downloaded zip i only got the 3 base core shader and an empty include folder, but the tool seems to do everything cause if i look in the browser console i can see more than what i got in the zip :/

![image](https://github.com/Non0reo/ImgToShader/assets/94833069/2a51e59b-812d-4906-b779-50c1a3b902f3)

**Comment by Non0reo** [comment]
Did you generate your pack in 1.19 or 1.20? I probably missed something somewhere. While I try to debug this thing, you can take the generated code and put it in the supposed include file

**Comment by vadim-soude** [comment]
Here are all my settings 
![image](https://github.com/Non0reo/ImgToShader/assets/94833069/a48b14b5-71d1-42ec-a86b-70f75718f773)

**Comment by Non0reo** [comment]
Okay, it should work now 👍
I forget to add two lines to my code but now the pack seems to be generated correctly. Tell me if the issue persists and if you manage to download your pack correctly

**Comment by vadim-soude** [comment]
I have fils in include now but when i load the pack in the version 1.18.2 (i set the version to 8 in the tool) i got all of this :/
![image](https://github.com/Non0reo/ImgToShader/assets/94833069/34080b25-53ff-43d9-a5dd-6d99f65cad9f)
The last error repeat forever again and again

**Comment by Non0reo** [comment]
I fixed the issue, sorry for the wait! That was harder to spot than I though but it was easy to implement. Try to generate another pack and let me know if it has worked this time 👍

**Comment by vadim-soude** [comment]
No problem, thank you so much it works now !! On a side note, the logo size think seems to be broken (changing the size don't do anything) in both >1.20 et <1.20, but it's not as urgent as what you fixed was !

**Comment by Non0reo** [comment]
The logo size slider is purely visual and affects only the generator preview. But you're right, I should make this more clear as it's not that obvious 😅
Thanks for your feedback and for using this generator
